name: c_panel
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  badges: ^2.0.1
  cached_network_image: ^3.1.0
  cloud_firestore: ^3.1.0
  cupertino_icons: ^1.0.2
  file_picker: ^4.2.3
  image_picker: ^0.8.4+1
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  firebase_storage: ^8.0.3
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^9.2.0
  get: ^4.3.7
  google_fonts: ^2.1.0
  like_button: ^2.0.3
  shared_preferences: ^2.0.5
  toggle_switch: ^1.3.0
  url_launcher: ^6.0.0
  connectivity: ^3.0.6


  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/3.jpg
    - assets/images/placeholder.png
    - assets/images/m.png
    - assets/images/w.png

